### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by CarlosUvaSilva** [nhcamp/EPL-Betting#2]
hello @nhcamp could you provide me your "last season standing file"?
I went to the website you mention but they only have the last 10 seasons and each one in a separate file. From what I understood you had a single file with these infos from *all* seasons

Thank you

**Comment by nhcamp** [comment]
Hi Carlos, I am away from my computer for the weekend but will address your question next week. Thanks!

**Comment by nhcamp** [comment]
Hi Carlos, after some digging through my file paths it looks like I was mistaken on where I got that data. Here is the link I pulled my particular data from: 
https://www.kaggle.com/limmen/premierleague-league-tables-188889-201617. 

There are also updated sets that have the same information but go closer to present time such as: https://www.kaggle.com/birdogd/english-football-premier-league-tables-19682019

Thanks for bringing my attention to this, I will update the information on the blog post!

**Comment by CarlosUvaSilva** [comment]
thank you so much
